### ISSUE TITLE
What are `Elements` module and `void` type?

### ISSUE THREAD

**Issue by vietlq** [rizo/dataflow#2]
Hi @rizo , I can't find the `Elements` module and `void` type. I followed the code in https://www.pusher.com/sessions/meetup/london-functional-programmers/stream-processing-with-coroutines-in-ocaml but I got errors after replacing `void` with `unit` and attempting to write `count ()`:

```
(* More useful examples *)
let count () =
  let rec loop n =
    yield n >> loop (n + 1)
  in loop 0
```

```
File "[63]", line 4, characters 4-27:
Error: This expression has type ('a, int, 'b) pipe
       but an expression was expected of type 'b
       The type variable 'b occurs inside ('a, int, 'b) pipe
Characters 65-88:
      yield n >> loop (n + 1)
      ^^^^^^^^^^^^^^^^^^^^^^^
```

Please kindly advise. Thanks.

**Comment by vietlq** [comment]
Here's the rest of the code before `count ()` to save you from typing:

```
(*
	https://www.pusher.com/sessions/meetup/london-functional-programmers/stream-processing-with-coroutines-in-ocaml
	http://rgrinberg.com/posts/monadic-generators-ocaml/
	https://github.com/rizo/dataflow
	https://monkey.org/~marius/implementing-python-style-generators-with-delimited-continuations.html
	http://ambassadortothecomputers.blogspot.com/2010/08/mixing-monadic-and-direct-style-code.html
	https://andrewray.github.io/iocamljs/full402.html
	https://github.com/rizo/awesome-ocaml
*)

(**************************************************************)

(* Core pipe types *)
type ('a, 'b, 'r) pipe =
  | Yield of ('b * ('a, 'b, 'r) pipe)
  | Await of ('a -> ('a, 'b, 'r) pipe)
  | Ready of 'r

(* Derived pipe types *)
type ('b, 'r) producer = (unit, 'b, 'r) pipe
type ('a, 'r) consumer = ('a, unit, 'r) pipe
type ('r) pipeline = (unit, unit, 'r) pipe

(**************************************************************)

(* Get a value from the pipe returning a new pipe *)
let rec (>>=) p f =
  match p with
  | Yield (b, p') -> Yield (b, p' >>= f)
  | Await k -> Await (fun a -> k a >>= f)
  | Ready r -> Ready (f r)

(* Sequence with two pipes *)
let (>>) p1 p2 = p1 >>= fun _ -> p2

(* Put a result value in the pipe *)
let return x = Ready x

(**************************************************************)

(* Pipe creation helpers *)
let empty = Ready ()
let yield b = Yield (b, empty)
let await = Await (fun b -> Ready b)

(**************************************************************)

(* Examples *)
let foobar = yield "foo" >> yield "bar"

let incr = await >>= fun n -> yield (n + 1)

let sum_pairs =
  await >>= fun a ->
  await >>= fun b ->
  yield (a + b)

(**************************************************************)
```

**Comment by rizo** [comment]
Hi @vietlq! Thanks for your interest in this library!

The code is a bit outdated and needs some corrections. I'll try to find time to improve it soon.

Regarding your questions:

* [Elements](https://github.com/rizo/elements) is a small convenience library. It's not strictly needed to implement pipes.
* `void` is an abstract type that _cannot_ be instantiated, it serves as a placeholder for impossible constructs (like a consumer that yields).

Depending on your needs you might be interested in a self-contained implementation I wrote to accompany my talk on Pipes. You can find it [here](https://gist.github.com/rizo/681cdf1bebf89bf49ab1d9eba628705a). It uses a delayed representation for yields to allow incremental processing of infinite streams.

I see you've collected a number of resources on this topic. You might find my bookmarks on [coroutines](http://pinboard.in/u:rizo/t:coroutines/), [pipes](http://pinboard.in/u:rizo/t:pipes) or [iteration](http://pinboard.in/u:rizo/t:iter) useful references too.

Let me know is this helps. Feel free to ask any questions regarding this library or streaming in general! :)

**Comment by rizo** [comment]
Oh, regarding your `count` issue. It seems like you have a small mistake in your bind implementation. The binding function `f` is expected to produce a pipe, you don't have to wrap its return value in a `Ready`:

The correct version is:

```ocaml
let rec (>>=) p (f: 'r -> ('a, 'b, 'r) pipe) =
  match p with
  | Yield (b, p') -> Yield (b, p' >>= f)
  | Await k -> Await (fun a -> k a >>= f)
  | Ready r -> f r
```

This way you should be able to implement your example.

**Comment by vietlq** [comment]
@rizo thank you! You made my day! I love the presentation and will take time to understand the ideas behind the design decisions you made. Are you doing any talks in London soon? I would love to attend.

**Comment by rizo** [comment]
I'm glad I could help.

I don't have any talks planned at the moment. But I'm currently organising the next London [ReasonML meetup](https://www.meetup.com/ReasonLDN/) (not announced yet) – it will focus on integration between Reason and OCaml from the tooling and community perspectives.

I've been extensively researching and playing with [different](https://github.com/rizo/streams) [streaming](https://github.com/rizo/iter) [models](https://github.com/rizo/transducers) over the last couple of years. If you have any particular questions about this area, don't hesitate to ask.

P.S. I see you're based in London, if you happen to be in the Old Street area feel free to ping me, I wouldn't mind grabbing a beer and chatting about pipes! :)

**Comment by vietlq** [comment]
Thanks @rizo I'm close to Old Street. Beer on me, I will DM you via email. I have loved pipes since I discovered Linux & Unix during uni days
